# generated by datamodel-codegen:
#   filename:  ScoreSchema.json
#   timestamp: 2024-09-18T11:26:03+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class MonBypassCost(BaseModel):
    toM: Optional[int] = None
    toB: Optional[int] = None
    toN: Optional[int] = None


class Role(BaseModel):
    name: Optional[str] = None
    protocol: Optional[str] = None
    type: str
    categ: str
    dataBreakCost: Optional[int] = None
    mCodeInjectCost: Optional[int] = None
    bCodeInjectCost: Optional[int] = None
    nCodeInjectCost: Optional[int] = None
    remoteSecrTheftCost: Optional[int] = None
    sessionProtectSecretIndex: List[bool]


class ProtBreakCosts(BaseModel):
    destruct: Optional[int] = None
    theft: Optional[int] = None
    tunnelProtocol: Optional[List[str]] = None
    tunnelDecrypt: Optional[int] = None
    tunnelDestroy: Optional[int] = None


class Input(BaseModel):
    sourceNodeIndex: int
    debug_sourceNodeName: str
    position: str
    roleIndex: int
    protBreakCosts: ProtBreakCosts
    isOpen: str


class FallbackActionIndex(BaseModel):
    toM: Optional[int] = None
    toB: Optional[int] = None
    toN: Optional[int] = None


class Node(BaseModel):
    name: str
    softwareClass: Optional[str] = None
    text: Optional[str] = None
    kernelIndex: Optional[int] = None
    nbRoles: int
    nbInputs: int
    nodeType: str
    plausThreshold: Optional[int] = None
    actThreshold: Optional[int] = None
    secrTheftCost: Optional[int] = None
    secrStore: List[bool]
    monBypassCost: MonBypassCost
    roles: List[Role]
    inputs: List[Input]
    fallbackActionIndex: FallbackActionIndex
    debug_fallbackActionNames: Optional[str] = None


class FallbackAction(BaseModel):
    name: str
    value: str


class Model(BaseModel):
    nbNodes: int
    nbSecrets: int
    secrets: List[str]
    nodes: List[Node]
    fallbackActions: List[FallbackAction]
